CREATE TYPE social_causes_type AS ENUM (
    'SOCIAL',
    'POVERTY',
    'HOMELESSNESS',
    'HUNGER',
    'HEALTH',
    'SUBSTANCE_ABUSE',
    'MENTAL',
    'BULLYING',
    'SECURITY',
    'EDUCATION',
    'GENDER_EQUALITY',
    'GENDER_BASED_VIOLENCE',
    'SEXUAL_VIOLENCE',
    'DOMESTIC_VIOLENCE',
    'WATER_SANITATION',
    'SUSTAINABLE_ENERGY',
    'DECENT_WORK',
    'INEQUALITY',
    'MINORITY',
    'MULTICULTURALISM',
    'DIVERSITY_INCLUSION',
    'INDIGENOUS_PEOPLES',
    'DISABILITY',
    'LGBTQI',
    'REFUGEE',
    'MIGRANTS',
    'ORPHANS',
    'CHILD_PROTECTION',
    'COMMUNITY_DEVELOPMENT',
    'DEPOPULATION',
    'OVERPOPULATION',
    'HUMAN_RIGHTS',
    'SUSTAINABILITY',
    'RESPONSIBLE_CONSUMPTION',
    'CLIMATE_CHANGE',
    'NATURAL_DISASTERS',
    'BIODIVERSITY',
    'ANIMAL_RIGHTS',
    'ARMED_CONFLICT',
    'PEACEBUILDING',
    'DEMOCRACY',
    'CIVIC_ENGAGEMENT',
    'JUSTICE',
    'GOVERNANCE',
    'CRIME_PREVENTION',
    'CORRUPTION',
    'OTHER',
    'RURAL_DEVELOPMENT',
    'VEGANISM',
    'BLACK_LIVES_MATTER',
    'ISLAMOPHOBIA',
    'ANTI_SEMITISM',
    'ABORTION',
    'EUTHANASIA',
    'NEURODIVERSITY',
    'SUSTAINABLE_COMMUNITIES',
    'BIODIVERSITY_LIFE_BELOW_WATER',
    'PEACE_JUSTICE',
    'COLLABORATION_FOR_IMPACT',
    'INNOVATION'
);

ALTER TYPE status_type ADD VALUE 'INACTIVE';

ALTER TABLE users
    ADD COLUMN password_expired boolean DEFAULT false,
    ADD COLUMN email_text character varying(255),
    ADD COLUMN phone character varying(255),
    ADD COLUMN mission text,
    ADD COLUMN bio text,
    ADD COLUMN description_search text,
    ADD COLUMN city text,
    ADD COLUMN country character varying(3),
    ADD COLUMN address text,
    ADD COLUMN geoname_id integer,
    ADD COLUMN mobile_country_code character varying(16),
    ADD COLUMN avatar uuid,
    ADD COLUMN cover_image uuid,
    ADD COLUMN social_causes social_causes_type[],
    ADD COLUMN identity_verified_at date,
    ADD COLUMN email_verified_at timestamp without time zone,
    ADD COLUMN phone_verified_at timestamp without time zone,
    ADD COLUMN deleted_at timestamp without time zone;
